---
inherit_from:
  - https://raw.githubusercontent.com/etalab/rubocop_api_entreprise/master/rubocop.yml

Metrics/BlockLength:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/pdfs/**/*'
    - 'spec/support/shared_examples/*'
    - 'spec/factories/**/*'
    - 'app/representers/**/*'
  ExcludedMethods:
    - 'describe'
    - 'context'
    - 'namespace'
