version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - .:/app
  
  sidekiq:
    build: .
    command: sidekiq:start
    depends_on:
     - redis
     - db
     - web
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379/1
      - TERM=dumb
      - secret_key_base=xxxxxxxxxx
    env_file:
      - .env
  
  web:
    build: .
    ports:
     - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379/1
      - TERM=dumb
      - secret_key_base=xxxxxxxxxx
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  dbdata:
