- '5751': Metz
- '5752': Sarreguemines
- '5753': Thionville
- '6751': Saverne
- '6752': Strasbourg
- '6851': Colmar
- '6852': Mulhouse
- '9711': Basse-Terre
- '9712': Pointe-à-Pitre
- '9721': Fort-de-France
- '9731': Cayenne
- '9741': St Denis de la Réunion
- '9742': St Pierre de la Réunion
- '9761': Mamoudzou
